/**
 * The disclaimer (shared): four points in both languages, plus the one-line
 * short form. Two surfaces show it — the help panel topic and the wizard's
 * summary step — and legal wording that exists twice always drifts, so both
 * read from here. It also keeps the copy readable from a spec: the renderer
 * dictionaries under src/ are outside tsconfig.node's file list.
 */
import type { UiLang } from './protocol';

export interface DisclaimerText {
  /** help panel topic title; numbered to sit last in the panel */
  title: string;
  lines: string[];
  /** what the wizard's summary step prints before the user enters the app */
  short: string;
}

export const DISCLAIMER: Record<UiLang, DisclaimerText> = {
  zh: {
    title: '13. 免责声明',
    lines: [
      '试验性质：本仓库是个人技术实验与开源研究产物，不是商业产品——没有服务等级承诺，没有合规审计，也不面向任何受监管场景。',
      '不通过本工具获取利益：软件本身免费、开源、不含内购或分成；调用大模型与语音识别产生的接口费用由你自己的 API Key 结算，与本仓库及其作者无关。',
      '使用后果由使用者承担：转录与回答均由 AI 生成，可能不准确、不完整甚至完全错误。任何因使用本工具导致的后果——面试 / 会议中的判断失误、纪律或法律风险、数据外泄、账号与费用损失——由使用者本人承担，作者不承担责任。',
      '自行确认合规：请在对方知情同意、且遵守所在机构规定的前提下使用；学校、公司或考试主办方明令禁止辅助工具的场景不要使用。Apache License 2.0 第 15、16 条（按现状提供、不提供担保、不赔偿损害）同样适用。',
    ],
    short:
      '免责：本工具是个人技术实验与开源研究产物，作者不通过它获取任何利益；转录与回答由 AI 生成、可能出错，任何使用后果由使用者本人承担。全文见主界面「帮助与教程 → 13. 免责声明」。',
  },
  en: {
    title: '13. Disclaimer',
    lines: [
      'Experimental by nature: this repository is a personal technical experiment and open-source research build, not a commercial product — no service-level commitment, no compliance audit, and it is not meant for regulated settings.',
      'No profit is taken from this tool: the software is free and open source, with nothing to buy and nothing to share; API costs for the LLM and for speech recognition are billed to your own key, unrelated to this repository or its author.',
      'Consequences belong to the user: transcripts and answers are generated by AI and may be inaccurate, incomplete or simply wrong. Any result of using this tool — a misjudgement in an interview or meeting, disciplinary or legal risk, leaked data, account or billing loss — is borne by the person using it; the author accepts no liability.',
      'Check your own compliance: use it where the other party is aware and your organisation allows it, and not where a school, employer or exam board bans assistive tools. Sections 15 and 16 of the Apache License 2.0 (provided "as is", no warranty, no damages) apply as well.',
    ],
    short:
      'Disclaimer: this tool is a personal technical experiment and open-source research build, and its author takes no profit from it; transcripts and answers are AI-generated and can be wrong, so any consequence of using it is borne by the user. Full text: "Help & guides → 13. Disclaimer".',
  },
};
